In [1]:
import pandas as pd

In [2]:
car_sales_missing = pd.read_csv('https://raw.githubusercontent.com/ashutosh-kedar/data_analysis_ml/refs/heads/main/data/car-sales-missing-data.csv')

In [3]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

## Filling the missing values with the mean/avg. Not the best practice but ok for sometimes

In [5]:
car_sales_missing['Odometer'].fillna(car_sales_missing['Odometer'].mean())

0    150043.000000
1     87899.000000
2     92302.666667
3     11179.000000
4    213095.000000
5     92302.666667
6     92302.666667
7     92302.666667
8     60000.000000
9     31600.000000
Name: Odometer, dtype: float64

## this returns a new series not affecting the original df. Can use inplace=True to update the original DF

In [13]:
car_sales_missing['Odometer'] = car_sales_missing['Odometer'].fillna(car_sales_missing['Odometer'].mean())

In [14]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [15]:
car_sales_missing.dropna()

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [16]:
car_sales_missing.dropna(inplace=True)

In [17]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [18]:
car_sales_missing.to_csv('car_sales_missing_dropped.csv')

In [19]:
car_sales_missing = pd.read_csv('https://raw.githubusercontent.com/ashutosh-kedar/data_analysis_ml/refs/heads/main/data/car-sales-missing-data.csv')

In [20]:
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [23]:
ratings = {'Toyota':2,'BMW':4,'Honda':8}
car_sales_missing['Ratings'] = car_sales_missing['Make'].map(ratings)
car_sales_missing

     Make Colour  Odometer  Doors    Price  Ratings
0  Toyota  White  150043.0    4.0   $4,000      2.0
1   Honda    Red   87899.0    4.0   $5,000      8.0
2  Toyota   Blue       NaN    3.0   $7,000      2.0
3     BMW  Black   11179.0    5.0  $22,000      4.0
4  Nissan  White  213095.0    4.0   $3,500      NaN
5  Toyota  Green       NaN    4.0   $4,500      2.0
6   Honda    NaN       NaN    4.0   $7,500      8.0
7   Honda   Blue       NaN    4.0      NaN      8.0
8  Toyota  White   60000.0    NaN      NaN      2.0
9     NaN  White   31600.0    4.0   $9,700      NaN

In [24]:
seats = pd.Series([2,4,2,7,8])

car_sales_missing['Seat'] = seats

car_sales_missing

     Make Colour  Odometer  Doors    Price  Ratings  Seat
0  Toyota  White  150043.0    4.0   $4,000      2.0   2.0
1   Honda    Red   87899.0    4.0   $5,000      8.0   4.0
2  Toyota   Blue       NaN    3.0   $7,000      2.0   2.0
3     BMW  Black   11179.0    5.0  $22,000      4.0   7.0
4  Nissan  White  213095.0    4.0   $3,500      NaN   8.0
5  Toyota  Green       NaN    4.0   $4,500      2.0   NaN
6   Honda    NaN       NaN    4.0   $7,500      8.0   NaN
7   Honda   Blue       NaN    4.0      NaN      8.0   NaN
8  Toyota  White   60000.0    NaN      NaN      2.0   NaN
9     NaN  White   31600.0    4.0   $9,700      NaN   NaN

In [28]:
car_sales_missing['Seat'] = car_sales_missing['Seat'].fillna(2)

In [29]:
car_sales_missing

     Make Colour  Odometer  Doors    Price  Ratings  Seat
0  Toyota  White  150043.0    4.0   $4,000      2.0   2.0
1   Honda    Red   87899.0    4.0   $5,000      8.0   4.0
2  Toyota   Blue       NaN    3.0   $7,000      2.0   2.0
3     BMW  Black   11179.0    5.0  $22,000      4.0   7.0
4  Nissan  White  213095.0    4.0   $3,500      NaN   8.0
5  Toyota  Green       NaN    4.0   $4,500      2.0   2.0
6   Honda    NaN       NaN    4.0   $7,500      8.0   2.0
7   Honda   Blue       NaN    4.0      NaN      8.0   2.0
8  Toyota  White   60000.0    NaN      NaN      2.0   2.0
9     NaN  White   31600.0    4.0   $9,700      NaN   2.0

In [30]:
car_sales = pd.read_csv('https://raw.githubusercontent.com/ashutosh-kedar/data_analysis_ml/refs/heads/main/data/car-sales.csv')
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [31]:
# When we use series as a new fields and the series len is less then the DF len, remaining get NaN
# if using python list it should be of same length

In [33]:
fuel_per_km = [3,5,2,4,7,6,9,1,4,5]
car_sales['Fuel per km'] = fuel_per_km
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Fuel per km
0  Toyota  White         150043      4   $4,000.00            3
1   Honda    Red          87899      4   $5,000.00            5
2  Toyota   Blue          32549      3   $7,000.00            2
3     BMW  Black          11179      5  $22,000.00            4
4  Nissan  White         213095      4   $3,500.00            7
5  Toyota  Green          99213      4   $4,500.00            6
6   Honda   Blue          45698      4   $7,500.00            9
7   Honda   Blue          54738      4   $7,000.00            1
8  Toyota  White          60000      4   $6,250.00            4
9  Nissan  White          31600      4   $9,700.00            5

In [37]:
car_sales.drop(columns=['Fuel per km'],inplace=True)

In [38]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [39]:
fuel_per_km = [3,5,2,4,7,6,9,1,4,5]
car_sales['Fuel per 100 km'] = fuel_per_km
car_sales

     Make Colour  Odometer (KM)  Doors       Price  Fuel per 100 km
0  Toyota  White         150043      4   $4,000.00                3
1   Honda    Red          87899      4   $5,000.00                5
2  Toyota   Blue          32549      3   $7,000.00                2
3     BMW  Black          11179      5  $22,000.00                4
4  Nissan  White         213095      4   $3,500.00                7
5  Toyota  Green          99213      4   $4,500.00                6
6   Honda   Blue          45698      4   $7,500.00                9
7   Honda   Blue          54738      4   $7,000.00                1
8  Toyota  White          60000      4   $6,250.00                4
9  Nissan  White          31600      4   $9,700.00                5

In [40]:
car_sales['Fuel Consumed'] = car_sales['Odometer (KM)']/100 * car_sales['Fuel per 100 km']
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Fuel per 100 km,Fuel Consumed
0,Toyota,White,150043,4,"$4,000.00",3,4501.29
1,Honda,Red,87899,4,"$5,000.00",5,4394.95
2,Toyota,Blue,32549,3,"$7,000.00",2,650.98
3,BMW,Black,11179,5,"$22,000.00",4,447.16
4,Nissan,White,213095,4,"$3,500.00",7,14916.65
5,Toyota,Green,99213,4,"$4,500.00",6,5952.78
6,Honda,Blue,45698,4,"$7,500.00",9,4112.82
7,Honda,Blue,54738,4,"$7,000.00",1,547.38
8,Toyota,White,60000,4,"$6,250.00",4,2400.00
9,Nissan,White,31600,4,"$9,700.00",5,1580.00

In [41]:
car_sales['Odometer (miles)'] = car_sales['Odometer (KM)'].map(lambda x: x/1.6)
car_sales

,Make,Colour,Odometer (KM),Doors,Price,Fuel per 100 km,Fuel Consumed,Odometer (miles)
0,Toyota,White,150043,4,"$4,000.00",3,4501.29,93776.875
1,Honda,Red,87899,4,"$5,000.00",5,4394.95,54936.875
2,Toyota,Blue,32549,3,"$7,000.00",2,650.98,20343.125
3,BMW,Black,11179,5,"$22,000.00",4,447.16,6986.875
4,Nissan,White,213095,4,"$3,500.00",7,14916.65,133184.375
5,Toyota,Green,99213,4,"$4,500.00",6,5952.78,62008.125
6,Honda,Blue,45698,4,"$7,500.00",9,4112.82,28561.250
7,Honda,Blue,54738,4,"$7,000.00",1,547.38,34211.250
8,Toyota,White,60000,4,"$6,250.00",4,2400.00,37500.000
9,Nissan,White,31600,4,"$9,700.00",5,1580.00,19750.000