In [1]:
import pandas as pd

In [2]:
car_sales = pd.read_csv('https://raw.githubusercontent.com/ashutosh-kedar/data_analysis_ml/refs/heads/main/data/car-sales.csv')
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [3]:
car_sales.dtypes  # this is a property which tells aboyt the data types of the columns in the df

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [6]:
car_sales.describe()  #by default it describes the numerical attributes

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [9]:
car_sales.describe(include=['object']) # describes the categorical attributes

C:\Users\HP\AppData\Local\Temp\ipykernel_11896\3986356287.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  car_sales.describe(include=['object']) # describes the categorical attributes

          Make Colour      Price
count       10     10         10
unique       4      5          9
top     Toyota  White  $7,000.00
freq         4      4          2

In [11]:
car_sales.describe(include='all')

          Make Colour  Odometer (KM)      Doors      Price
count       10     10      10.000000  10.000000         10
unique       4      5            NaN        NaN          9
top     Toyota  White            NaN        NaN  $7,000.00
freq         4      4            NaN        NaN          2
mean       NaN    NaN   78601.400000   4.000000        NaN
std        NaN    NaN   61983.471735   0.471405        NaN
min        NaN    NaN   11179.000000   3.000000        NaN
25%        NaN    NaN   35836.250000   4.000000        NaN
50%        NaN    NaN   57369.000000   4.000000        NaN
75%        NaN    NaN   96384.500000   4.000000        NaN
max        NaN    NaN  213095.000000   5.000000        NaN

In [12]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [13]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [14]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [15]:
car_sales.sum(numeric_only=True)

Odometer (KM)    786014
Doors                40
dtype: int64

In [17]:
price_series = pd.Series([232,243,2654])
price_series.sum()

np.int64(3129)

In [18]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [19]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [21]:
len(car_sales)

10

In [22]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [24]:
car_sales.tail()

     Make Colour  Odometer (KM)  Doors      Price
5  Toyota  Green          99213      4  $4,500.00
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [25]:
car_sales.to_csv('exported_car_sales.csv',index=False)

In [27]:
exported_car_sales = pd.read_csv('exported_car_sales.csv')
exported_car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [29]:
car_sales['Colour'].describe()  # describing categorical attribute

count        10
unique        5
top       White
freq          4
Name: Colour, dtype: object

In [31]:
car_sales['Make'].value_counts()

Make
Toyota    4
Honda     3
Nissan    2
BMW       1
Name: count, dtype: int64

In [32]:
car_sales['Make'].unique()

<StringArray>
['Toyota', 'Honda', 'BMW', 'Nissan']
Length: 4, dtype: str

In [34]:
car_sales['Make'].nunique()

4

In [38]:
# getting normalized values counts

car_sales['Colour'].value_counts(normalize=True) * 100

# this gives the percent of values for the particular category

Colour
White    40.0
Blue     30.0
Red      10.0
Black    10.0
Green    10.0
Name: proportion, dtype: float64

In [40]:
car_sales['Colour'].value_counts(dropna=False)
# If there is NA in the series it will include them also

Colour
White    4
Blue     3
Red      1
Black    1
Green    1
Name: count, dtype: int64

In [44]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [51]:
categorical_cols = car_sales.select_dtypes(include=['object','str']).columns

for column in categorical_cols:
    print(f'\n{column}:\n')
    print(car_sales[column].value_counts(dropna=False))

Make:

Make
Toyota    4
Honda     3
Nissan    2
BMW       1
Name: count, dtype: int64

Colour:

Colour
White    4
Blue     3
Red      1
Black    1
Green    1
Name: count, dtype: int64

Price:

Price
$7,000.00     2
$4,000.00     1
$5,000.00     1
$22,000.00    1
$3,500.00     1
$4,500.00     1
$7,500.00     1
$6,250.00     1
$9,700.00     1
Name: count, dtype: int64

## Viewing the data